{{- if .Values.secretProviderClasses.djangoSettings.create }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClasses.djangoSettings.name | default "django-settings-secrets" }}
  # Namespace omitted on purpose; Helm will place it in .Release.Namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secretProviderClasses.djangoSettings.aws.objectName | quote }}
        objectType: {{ .Values.secretProviderClasses.djangoSettings.aws.objectType | default "secretsmanager" | quote }}
        objectStage: {{ .Values.secretProviderClasses.djangoSettings.aws.objectStage | default "AWSCURRENT" | quote }}
        jmesPath:
        {{- range $k := .Values.secretProviderClasses.djangoSettings.secretKeys }}
          - path: {{ $k | quote }}
            objectAlias: {{ $k | quote }}
        {{- end }}
    region: {{ .Values.secretProviderClasses.djangoSettings.aws.region | default "ap-northeast-2" | quote }}
  secretObjects:
    - secretName: {{ .Values.secretProviderClasses.djangoSettings.secretName | default "django-settings-secrets" }}
      type: {{ .Values.secretProviderClasses.djangoSettings.secretType | default "Opaque" }}
      data:
      {{- range $k := .Values.secretProviderClasses.djangoSettings.secretKeys }}
        - key: {{ $k | quote }}
          objectName: {{ $k | quote }}
      {{- end }}
{{- end }}
