{{- if .Values.serviceAccounts.secretAccess.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.secretAccess.name | default "secret-access" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccounts.secretAccess.iamRoleArn | quote }}
    {{- with .Values.serviceAccounts.secretAccess.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.secretAccess.automount | default false }}
{{- end }}